### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/garbage#1]
Hey mate, what's this? 
As far as I see it's some good quality garbage so I'm gonna download it. Hooooly shit it has a lot of aliens...

**Comment by thewierdnut** [comment]
This is the [Galactic War Plugin](https://github.com/1010todd/Galactic-War/) from @1010todd, except with the images converted to compressed textures so that it takes up less memory on a mobile device. 

Its mostly just a test to see if the texture compression works for a plugin. I meant for somebody else to test it, but you are welcome to give your feedback as well. 

Basically, I want to know the following:
1) How much ram does your device have?
2) How much ram does endless sky use after loading it?
3) Does it load at all?
4) Does it load faster than the vanilla plugin?

**Comment by YiffLord** [comment]
Oh well. Hold on.

**Comment by YiffLord** [comment]
Yeah, that concludes it. Double checkd in case I made a mistake or something.

**Comment by thewierdnut** [comment]
hm... it loads fine on my phone, which also has 3 gig of ram. 

How did you load it? Did you make a zip out of that folder and import it? What is the root folder within your zip file?

**Comment by YiffLord** [comment]
> hm... it loads fine on my phone, which also has 3 gig of ram.
> 
> How did you load it? Did you make a zip out of that folder and import it? What is the root folder within your zip file?

I selected it as I did with any other plugin, exactly the way it was downloaded from GitHub.

**Comment by YiffLord** [comment]
I will triple check, mayhaps I am doing something wrong.

**Comment by thewierdnut** [comment]
hm... you need to zip *just* the Galactic-War-ktx-13582 folder, not the garbage folder.

**Comment by YiffLord** [comment]
> hm... you need to zip _just_ the Galactic-War-ktx-13582 folder, not the garbage folder.
> 
> I would have just provided the zip file directly, but github frowns on large files.

Owh that's it then. Yeah I'm gonna do that.

**Comment by YiffLord** [comment]
So now doing it properly....
1. 3GB
2. Vanilla 400mb / GW 1.5-2GB / Garbage 1.3-1.6GB (According to my device's memory optimizer)
3. It loads.
4. Vanilla 1-2s / GW 40s-1m / Garbage ~15s avg. Pretty good improvement.

**Comment by thewierdnut** [comment]
hm... I expect GW to be about 1.6 GB, and garbage to be about 700 MB. I wonder if your device is selectively decompressing some of the textures on the fly.

**Comment by thewierdnut** [comment]
Thanks for the testing and the numbers.

**Comment by YiffLord** [comment]
Probably, I don't know. Sure thing is that compression of yours makes quite the difference. From 2GB to 1.3GB there is a long way.
